COVID-19-Data-Tracker
dami1080/covid19-data-tracker pull request #1
Opened 2021-11-25 17:01 UTC by dami1080

In this project, I:

- Created the React App.
- Selected the MMediaGroup Covid-19 API for Data
- Installed basic dependencies (React-Redux, Redux Logger and React Router).
- Created routes and navigations for the app
- Created the directory for all Redux state slice files.
- Created routes and view components for the Home and Details page.
- Fetched data from the API when the application starts.
- Dispatched an action to store the selected data in the Redux store.
- Used useSelector(), Redux Hook, to select the state slices and render countries and country details in corresponding routes.
- Implemented the Filter for filtering the number of confirmed cases.
- Write unit tests with Jest and React Testing Library
- Styled the application using plain CSS and React Bootstrap.
- Integrated linters.

[video demo](https://www.loom.com/share/083e86989baa424a96f8ce70817db5c3)

2021-11-25 17:49 UTC, Davidosky007 requested changes
## Hi @dami1080 👋, 

Good job so far! 💪 
* No linter errors ✔️ 
* Descriptive commit messages ✔️ 
* Well written PR ✔️ 
* Proper use of git-flow ✔️ 
* Cool design ✔️ 
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
* Kindly add a highlight of some interesting piece of code or something you built that you are very proud of 🙏 .
_Check the comments under the review._
![almost-jumpin-gif](https://user-images.githubusercontent.com/52497246/143484795-afe7c7f3-72a4-412b-a669-01dde8f1f90b.gif)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
wever, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-25 17:49 UTC, Davidosky007 commented on src/App.js
> +      </Router>
* Kindly ensure The project is a single page application (SPA) using react-router-dom to serve each page without reloading as currently, it reloads when i visit the details page.

2021-11-25 17:49 UTC, Davidosky007 commented on src/tests/TotalCard.test.js
> +    )
* Kindly perform a mocking data fetching and Redux Store connection as stated in the project [requirement](https://github.com/microverseinc/curriculum-react-redux/blob/main/capstone/react_capstone.md#:~:text=You%20may%20need,the%20Redux%20Store.).

2021-11-27 07:22 UTC, ArthurGC requested changes
# Required Changes ♻️ :warning: 
Hi  @dami1080 

Great work on making the changes requested by a previous reviewer. 👏 
You've done well implementing some of the requested changes but there are some issues that you still need to work on to go to the next project but you are almost there! 

![](https://media0.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif)

## Good Points :+1: :
Great job following most of the first reviewer's suggestions :heavy_check_mark:

## Aspects to improve 🔴 
_Check the comments under the review._

- [ ] **As the previous reviewer said. Please, add a highlight of some interesting piece of code or something you built that you are very proud of in your video demo.**


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-11-27 07:22 UTC, ArthurGC commented on src/redux/countries/countries.js
> +
- [OPTIONAL] It would be better if you remove `console.log` to follow the best practices in coding. ♻️

2021-11-27 09:46 UTC, Mihndim2020 approved these changes
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi @dami1080, 

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-27 09:54 UTC, merged